naam = input("wat is uw naam? ")
adres = input("wat is je adres? ")
postcode = input("wat is je postcode? ")
woonplaats = input("wat is je woonplaats? ")

print("--------------------------------------")
print("|")
print("|")
print("|" + str(naam))
print("|" + str(adres))
print("|" + str(postcode))
print("|" + str(woonplaats))
print("|")
print("|")
print("--------------------------------------")